steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/table-tennis-admin:${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'table-tennis-admin'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/table-tennis-admin:${_IMAGE_TAG}'
    - '--region'
    - 'asia-east1'
    - '--platform'
    - 'managed'

images:
  - 'gcr.io/${PROJECT_ID}/table-tennis-admin:${_IMAGE_TAG}'
