steps:
  - name: 'node:20.10.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        yarn install && yarn build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$REPO_NAME:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$REPO_NAME:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - $REPO_NAME
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$REPO_NAME:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

substitutions:
  _REGION: asia-east1
  _REPOSITORY: ninja
