steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/table-tennis-admin:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'table-tennis-admin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/table-tennis-admin:$SHORT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/table-tennis-admin:$SHORT_SHA'
