steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git fetch --tags
        git describe --tags `git rev-list --tags --max-count=1` > .IMAGE_TAG

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMAGE_TAG=$(cat .IMAGE_TAG)
        docker build -t gcr.io/$PROJECT_ID/table-tennis-admin:$IMAGE_TAG .

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMAGE_TAG=$(cat .IMAGE_TAG)
        gcloud run deploy table-tennis-admin --image gcr.io/$PROJECT_ID/table-tennis-admin:$IMAGE_TAG --region asia-east1 --platform managed --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/table-tennis-admin:$COMMIT_SHA'
