version: "3.3"

services:
  table-tennis-admin:
    image: ghcr.io/li-ninja/table-tennis-admin:latest
    ports:
      - 5651:8080
    restart: always
    container_name: ninja-table-tennis-admin
    networks:
      #  set same network as the nginx service
      - my-network

networks:
  my-network:
    external: true
