version: "3.3"

services:
  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    ports:
      - 80:8080
    restart: always

  backend:
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./.env.backend:/app/.env:ro

  ttAdminFrontend:
    image: ${TT_ADMIN_FRONTEND_IMAGE_NAME}
    ports:
      - 81:9000
    restart: always
